### ISSUE TITLE
on the client machine,how to connect the tlstun server?

### ISSUE THREAD

**Issue by briteming** [parazyd/tlstun#2]
tlstun only have server mode,but don't have client mode?

**Comment by parazyd** [comment]
Can you explain your usecase to me a little bit? Perhaps this is something I can implement.

**Comment by briteming** [comment]
hi.

the following usage is on server,right?
Usage of ./tlstun:
  -cacert string
        Path for CA certificate file (default "ca.pem")
  -cert string
        Path for Certificate file (default "server.pem")
  -forward string
        Forward address (default "127.0.0.1:72")
  -key string
        Path for Key file (default "server-key.pem")
  -listen string
        Listen address (default "127.0.0.1:7443")

there is no client version of tlstun?
i want tlstun to act like stunnel (the famous stunnel app from stunnel.org). can it be implemented?

**Comment by parazyd** [comment]
I implemented this commit: 66a824d9fd7100a33075cd9d6bb4b0e6000e9c09 , which adds the `-forwardtls` flag.

I manage to use it with the following:

```
./tlstun -forwardtls -forward parazyd.org:443 -listen localhost:9099 -notls
curl -H "Host: parazyd.org" localhost:9099
```
This gives me the plain website.

Does this serve your usecase?

**Comment by briteming** [comment]
do u know in china,there is a so-called GFW(great firewall of china) which blocks many 'sensitive' websites such as facebook,youtube?
i want a tool to cross the gfw to visit the blocked websites.
your tlstun can  do that?

**Comment by parazyd** [comment]
tlstun is not a tool for censorship circumvention. You might want to look into some proxy implementations like shadowsocks, Tor with Pluggable Transports, or even Wireguard.

**Comment by parazyd** [comment]
For YouTube, you could also try alternative interfaces like Invidious. For example there is one instance running at: https://yewtu.be/feed/trending
